### ISSUE TITLE
Logo von Pro7 Maxx

### ISSUE THREAD

**Issue by MegaV0lt** [3PO/Senderlogos#14]
Der Sender Prosieben MAXX HD hat sich anscheinend umbenannt. Das Logo wird nicht mehr angezeigt. Name in der Kanalliste ist nun Pro7 MAXX HD

**Comment by 3PO** [comment]
Erledigt.
--> https://github.com/3PO/Senderlogos/commit/6aca20ac151253c3bdf1ef91e2956b989780f6e2
