### ISSUE TITLE
BR hat sich mal wieder umbenannt

### ISSUE THREAD

**Issue by MegaV0lt** [3PO/Senderlogos#16]
Die Kanäle des BR haben mal wieder neue Namen bekommen:

```
BR Fernsehen Süd 
BR Fernsehen Süd HD
BR Fernsehen Nord
BR Fernsehen Nord HD 
```

**Comment by MegaV0lt** [comment]
PS: Logos: https://de.wikipedia.org/wiki/Bayerischer_Rundfunk#BR_Fernsehen

**Comment by 3PO** [comment]
Erledigt.

https://github.com/3PO/Senderlogos/commit/7b18d0d36472b81f3a4928b52d0b14d0e7d7c744
