### ISSUE TITLE
Senderlogos

### ISSUE THREAD

**Issue by MegaV0lt** [3PO/Senderlogos#2]
RTL Crime hat ein ReDesign durchgeführt. Das Senderlogo ist nun auch verändert: http://j.mp/1Hx7fbW

**Comment by MegaV0lt** [comment]
Auch RTL Living ist neu gestaltet: http://j.mp/1Hx7hAE

**Comment by MegaV0lt** [comment]
Und RTL Passion: http://j.mp/1Hx7mnI

**Comment by MegaV0lt** [comment]
Auch bei AXN gab es ein neues Logo: http://j.mp/1OxH1FA

**Comment by MegaV0lt** [comment]
Das n-tv HD glaube ich ist auch anders: http://j.mp/1OxHl7d

**Comment by 3PO** [comment]
Erledigt

--> https://github.com/3PO/Senderlogos/commit/269db37ee4232f518694c7f7a426eb2af6862670
