### ISSUE TITLE
Feature: Optipng

### ISSUE THREAD

**Issue by MegaV0lt** [3PO/Senderlogos#3]
Ist es eine Option das Programm Optipng in den Standardeinstellungen über die Logos laufen zu lassen? Es könnte sich eine deutliche Reduzierung der Größe (ohne Qualitätsverlust) ergeben...

Bei meinen Skinlogos hat das 30-40% gebracht

**Comment by 3PO** [comment]
Klar ist das eine Option, Du kannst über die Logos alles drüber laufen lassen, was auch immer Du für richtig hälst.
