### ISSUE TITLE
Atlanic +1 HD name ändern

### ISSUE THREAD

**Issue by MegaV0lt** [3PO/Senderlogos#31]
Sky Atlantic +1 HD,SkyAtlantic1HD;SKY:11797:HC910M2O35P0S1:S19.2E:27500:511=27:0;515=deu@106,516=eng@106:32:9C4,9AF,98C:144:133:16:0
Das Logo ist aber 
sky atlantic+1 hd.png
Bitte ein Leerzeichen vor dem +1 einfügen

**Comment by 3PO** [comment]
Erledigt!

https://github.com/3PO/Senderlogos/commit/c6b5e650434c1678ce3a6228ea70b0f4b15b7320
