### ISSUE TITLE
Sky 1 HD

### ISSUE THREAD

**Issue by MegaV0lt** [3PO/Senderlogos#33]
Der am 3.11. startende Kanal Sky 1 HD. Logo: http://j.mp/2eFLidU
Das Logo für den SD-Kanal wird scon in der Liste angezeigt

**Comment by 3PO** [comment]
Erledigt!

--> https://github.com/3PO/Senderlogos/commit/11b3608726f4e1e6af87ab0bf23c4f368664a4cc
