### ISSUE TITLE
Neues Logo und Name

### ISSUE THREAD

**Issue by MegaV0lt** [3PO/Senderlogos#38]
RTLNitroHD hat einen neuen Namen (Nitro HD) und ein neues Logo:
https://de.wikipedia.org/wiki/Nitro_(Fernsehsender)

**Comment by 3PO** [comment]
Gibt es auch irgendwo ein Logo für Nitro HD?

Ich finde nur ein Logo für Nitro.

**Comment by MegaV0lt** [comment]
Finde auch keines... Auf Lyngsat ist nichts zu finden :(

**Comment by 3PO** [comment]
Es gibt weder auf der Homepage des Senders, noch auf Lyngsat-logo, noch auf der Site von HD+ ein entsprechendes Logo für "Nitro HD".

Man könnte ja für HD und SD das gleiche Logo nehmen, zumindest mal solage, bis es ein Logo für HD gibt?

**Comment by MegaV0lt** [comment]
Klar. Das ist besser als nichts. Bei KabelBW gibt es was, das ist aber leider nicht verwendbar, da nicht transparent und zu klein: http://j.mp/2uvIlZ0

**Comment by 3PO** [comment]
Ich habe es jetzt mal so gelöst: https://github.com/3PO/Senderlogos/commit/4475a83266e6976d687bbd92301543c30fc1d387

Ich hoffe, dass das so passt?

**Comment by MegaV0lt** [comment]
Klar. Danke!
