### ISSUE TITLE
new logos

### ISSUE THREAD

**Issue by 9000h** [3PO/Senderlogos#4]
es fehlen noch
DW
ATV SD
R9 Oesterreich HD
BBC World News Europe HD
TLC HD Austria
Big Brother 24 Stunden
Pro7 MAXX Austria
Sat.1 Gold Österreich
RTL NITRO A
Fashion Television
Cherie 25 (cherie25 ist falsch)
iTELE
RMC Decouverte
M6 HD
pearl.tv HD Shop
Cartoon Network HD (bei KDG)
....

**Comment by 3PO** [comment]
> DW

Erledigt!

> ATV SD

Ist schon immer drin.

> R9 Oesterreich HD

Erledigt!

> BBC World News Europe HD

Bitte prüfen, ob das passt, habe dazu nichts wirklich sinnvolles gefunden.

> TLC HD Austria

für TLC HD Austria gibt es kein eigenes Logo.
--> TLC HD zu TLC HD Austria kopiert.

> Big Brother 24 Stunden

Eledigt!

> Pro7 MAXX Austria

Eledigt!

> Sat.1 Gold Österreich

Eledigt!

> RTL NITRO A

für RTL NITRO A gibt es kein eigenes Logo.
--> RTL NITRO zu RTL NITRO A kopiert.

> Fashion Television

Ist schon immer drin.

> Cherie 25 (cherie25 ist falsch)

???

> iTELE

Erledigt!

> RMC Decouverte

Erledige!

> M6 HD

Erledigt!

> pearl.tv HD Shop

Erledigt!

> Cartoon Network HD (bei KDG)

--> Ich habe kein KDG.

https://github.com/3PO/Senderlogos/commit/84215bd2333a1f8469af76fe4863fe8795364893

**Comment by 9000h** [comment]
Hi,
Danke

ATV SD ist der neue "ATV3" jetzt mit Kennung ATV Austria

```
ATV Austria;M7 Group:12721:HC23M5O20P0S1:S19.2E:23500:601=27:163=deu@3:0:1817,100,500:12902:53:1119:0
```

Sky INFO ist auch noch nicht dabei

```
Sky INFO;SKY:11171:HC34M5O35P0S1:S19.2E:22000:511=27:0;515=deu@106:32:0:141:133:9:0
```

CU
9000h

**Comment by 3PO** [comment]
> ATV SD ist der neue "ATV3" jetzt mit Kennung ATV Austria

Ist das das Selbe wie,

`ATV;ATV+:12692:HC56M2S0:S19.2E:22000:506=2:507=deu@3:509:648,650,D95,D98,9C4,98C:13012:1:1117:0`

nur mit M7 als Provider?

**Comment by 9000h** [comment]
Hi,
nein ist was neues
http://diepresse.com/home/kultur/medien/4673621/Trotz-Verlusten_ATVEigentumer-will-ATV-3-starten
CU
9000h

**Comment by 3PO** [comment]
> Sky INFO ist auch noch nicht dabei

Erledigt!  -->    https://github.com/3PO/Senderlogos/commit/7a71079dee02fa6e918d864ff754b4d373509f65

**Comment by 3PO** [comment]
Zu "ATV 3" finde ich leider kein Logo. :(

**Comment by 9000h** [comment]
ist ok
