### ISSUE TITLE
SyFy - Neues Logo

### ISSUE THREAD

**Issue by MegaV0lt** [3PO/Senderlogos#40]
Seit dem 1.9.2017 hat auch SyFy ein neues Logo bekommen: http://j.mp/2x4Wo8M
Wieder ohne HD-Logo. Scheint wohl seit neuestem zum guten Ton zu gehören....

**Comment by MegaV0lt** [comment]
Hier der Link zum deutschen SyFy: http://j.mp/2x4HMqi

**Comment by 3PO** [comment]
Ich habe es jetzt mal so gelöst: --> https://github.com/3PO/Senderlogos/commit/f620c5f75d1da9c823956d72df2e68fd157bee4d
