### ISSUE TITLE
"oe24.tv" and "n24 doku" missing

### ISSUE THREAD

**Issue by davie2000** [3PO/Senderlogos#44]
oe24.tv
https://lh3.googleusercontent.com/zrnjGXw8bP7pTjGGpIcrxvHPll3aTXOFlqOoPzJ3DzAcvdZZeoPSk_R1eoZJKkwStcpf=w300

n24 doku
http://s3.amazonaws.com/cision-wp-files/de/wp-content/uploads/2016/07/21142507/n24_credit-obs2FWeltN24-GmbH-1210x423.jpg

Vielen Dank schon jetzt fürs Hinzufügen!

**Comment by 3PO** [comment]
Erledigt.

--> https://github.com/3PO/Senderlogos/commit/1319af0e7655b40cc171e1933bae19e84339e4fb

**Comment by davie2000** [comment]
Hey, vielen Dank für die schnelle Bearbeitung!
