### ISSUE TITLE
N24 hat sich umbenannt

### ISSUE THREAD

**Issue by MegaV0lt** [3PO/Senderlogos#47]
Neues Logo: https://de.wikipedia.org/wiki/Welt_(Fernsehsender)#Senderlogos

**Comment by 3PO** [comment]
Erledigt. --> https://github.com/3PO/Senderlogos/commit/b93ed0acb4f108b7f9137774269655c9fd94aebe

Ein Logo für "welt HD" scheint es (noch) nicht zu geben, deshalb habe ich beide gleich gemacht.

**Comment by MegaV0lt** [comment]
Dass Logos ohne HD sind scheint mittlerweile üblich zu sein. Nitro z. B. 
Danke für die schnelle Umsetzuzng!
