### ISSUE TITLE
ARD-alpha HD Logo fehlt

### ISSUE THREAD

**Issue by MegaV0lt** [3PO/Senderlogos#57]
Das Logo für ARD-alpha HD fehlt noch:
https://de.wikipedia.org/wiki/ARD-alpha#Senderlogos

**Comment by 3PO** [comment]
ERLEGIGT:

--> https://github.com/3PO/Senderlogos/commit/dbd057456e84e3b6ee561fdcbf8b9858fa4d1ec1

Danke!
