### ISSUE TITLE
Aus Anixe wurde Anixe+

### ISSUE THREAD

**Issue by MegaV0lt** [3PO/Senderlogos#61]
https://www.fernsehserien.de/news/aus-anixe-wird-anixe-sender-relaunch-mit-erweiterter-mediathek

Anixe HD und Anixe+ senden verschiedene Programme!

**Comment by 3PO** [comment]
Erledigt: --> https://github.com/3PO/Senderlogos/commit/13235873328a20dac4b55fdfddf73432c2b96e44
